### ISSUE TITLE
why using h5 file? directly using csv is not efficient?

### ISSUE THREAD

**Issue by xuChenSJTU** [reczoo/BARS#26]
Hi,

I am trying to use this to reproduce results of some benchmarks. But h5 file does not work well on our computation system.
Is there any reason why using h5 file? Could we directly use csv file in constructing train, val and test data?
directly using csv is not efficient?

Thanks~

**Comment by zhujiem** [comment]
Yes. h5 is used for IO consideration. It will be better if you have multi-hot fields with each has a vector. You can use csv, but just needs to rewrite the data loader.
