### ISSUE TITLE
the method of embedding table initialization for different CTR prediction models

### ISSUE THREAD

**Issue by Zeng-B-B** [reczoo/BARS#27]
How to choose the  method of embedding table Initialization? if I choose the xavier_uniform method, the AUC is always 0.5 when I run the code of SAM model.But when I run the code of other models (AutoInt, FiGNN, AFN)using the xavier_uniform method,  the results are good and normal. 
I see that the method using in the project is normal initialization(`embedding_initializer="partial(nn.init.normal_, std=1e-4)"`). Is all model the mehod?

**Comment by zhujiem** [comment]
Yes, basically we did not tune the embedding_initializer. It is normal by default.
