### ISSUE TITLE
I need to use fusictr2.0+for DIN/DIEN benchmark testing. How should I write the run_expid.py file

### ISSUE THREAD

**Issue by dengyayin** [reczoo/BARS#29]

**Comment by zhujiem** [comment]
You can refer to https://github.com/reczoo/BARS/tree/main/ranking/ctr/DIEN/DIEN_amazonelectronics_x1#code

**Comment by dengyayin** [comment]
What is the reason for the error message when introducing RankDataLoader？

import os
os.chdir(os.path.dirname(os.path.realpath(__file__)))
import sys
import logging
import fuxictr_version
from fuxictr import datasets
from datetime import datetime
from fuxictr.utils import load_config, set_logger, print_to_json, print_to_list
from fuxictr.features import FeatureMap
**from fuxictr.pytorch.dataloaders import RankDataLoader**
from fuxictr.pytorch.torch_utils import seed_everything
from fuxictr.preprocess import FeatureProcessor, build_dataset
import src
import gc
import argparse
import os
from pathlib import Path

This is a specific error message：
Traceback (most recent call last):
  File "/home/dyy/Prediction-Cache/FuxiCTR/model_zoo/DIEN/run_expid.py", line 35, in <module>
    from fuxictr.pytorch.dataloaders import RankDataLoader
ImportError: cannot import name 'RankDataLoader' from 'fuxictr.pytorch.dataloaders' (/home/dyy/miniconda3/envs/deepCtr/lib/python3.7/site-packages/fuxictr/pytorch/dataloaders/__init__.py)

**Comment by zhujiem** [comment]
Please use the exactly the same version specified in the above running steps. In your case, you use run_expid.py in mater but use an old version fuxictr package installed.

**Comment by dengyayin** [comment]
The. py file requires the version of fusictr to be>=2.2.0, but currently the highest version that can be installed is 2.1.3. How should I solve this problem?
And there will be an error when installing fusictr2.0+version. Is there a lot of missing files in the package now?
![Uploading QQ图片20240318141746.png…]()
