### ISSUE TITLE
About the DIEN sequence model

### ISSUE THREAD

**Issue by dengyayin** [reczoo/BARS#32]
I want to run datasets such as Criteo and Avazu on the DIEN sequence model. How should I modify the parameters in the model_config.yaml file? Looking forward to your reply！

**Comment by zhujiem** [comment]
DIEN  need user behavior sequence as input, but both Criteo and Avazu have no sequence features. So you should use other datasets such as [TaobaoAd_x1](https://github.com/reczoo/Datasets/tree/main/Taobao/TaobaoAd_x1), [AmazonElectronics_x1](https://github.com/reczoo/Datasets/tree/main/Amazon/AmazonElectronics_x1), [KuaiVideo_x1](https://github.com/reczoo/Datasets/tree/main/KuaiShou/KuaiVideo_x1)
