### ISSUE TITLE
Is fuxctr<=1.x a must?

### ISSUE THREAD

**Issue by ywangwxd** [reczoo/BARS#35]
I noticed that the latest version of fuxictr was 2.3.x. Does this repo run on fuxictr 2.3.x?
By the way, I nocited that many of the requirement file in this git group do not specify version. 
I strongly suggest doing it. I have encountered problems of version compatiblity of some depended libraries.
I have to try downgrading version by version to test which version is compatible.

**Comment by zhujiem** [comment]
Each experiment may be executed with a different FuxiCTR version. Pls follow the hands-on readme in each folder to set up the environment.
