### ISSUE TITLE
Why is it that most model directories do not have a file named `run_expid.py`？

### ISSUE THREAD

**Issue by Zeng-B-B** [reczoo/BARS#39]
I found that most model directories do not have a file named `run_expid.py`. For example, I wanted to run the `DIEN` model on the `amazonelectronics_x1` dataset. Following the steps described in the `readme.md`, I installed the corresponding version of `fuxictr`, but did not find the `run_expid.py` file. So, I copied the `run_expid.py` from the directory of the `DCN` model, but still encountered errors during execution:
```
Traceback (most recent call last):
  File "F:\RecommendationSystem\BARS\ranking\ctr\DIEN\run_expid.py", line 12, in <module>
    from fuxictr.features import FeatureMap, FeatureEncoder
ImportError: cannot import name 'FeatureEncoder' from 'fuxictr.features' (E:\Anaconda\envs\py310-torch2\lib\site-packages\fuxictr\features.py)
```

This is because the `fuxictr` version specified in the `DIEN` model directory's `readme.md` is `2.0.2`, while the `DCN` model requires version `1.1.0`, leading to the `run_expid.py` in the `DCN` model directory being incompatible with the `DIEN` model. How can this be resolved?It seems that the API has changed between different versions of `fuxictr`. Could you provide a universal `run_expid.py` file? Or could you provide a `run_expid.py` file for each model?

**Comment by zhujiem** [comment]
Please follow the instruction to cd to the model_zoo folder to run:
cd FuxiCTR/model_zoo/DIEN

FuxiCTR is the directory you download.
